### ISSUE TITLE
Question 3 both answers are correct

### ISSUE THREAD

**Issue by Preston-Hunter** [learn-co-curriculum/phase-4-quiz-rails-fundamentals#1]
### Canvas Link

https://learning.flatironschool.com/courses/6267/quizzes/45943

### Concern

How do we parameterize different parts of our routes?  is the question

only difference is  <string:username> vs <username>
both use the angle brackets. When choosing wrong answer, hint is given as adding angle brackets (which are already in answer). When choosing correct answer, response is given as "We can also define the username type as a  string, int, float, or path (string with slashes) by specifying this in the route" which says the string: component of correct answer is optional

### Suggested Changes

change <username> to username to make the answer actually incorrect

**Comment by lizbur10** [comment]
@professor-ben @pgill97 Looks like the Flask Fundamentals quiz is incorrectly linked to this repo

**Comment by pgill97** [comment]
Fixed the question.
