### ISSUE TITLE
Quiz Question Issue

### ISSUE THREAD

**Issue by NomadLyfe** [learn-co-curriculum/phase-4-quiz-rails-fundamentals#2]
### Canvas Link

https://learning.flatironschool.com/courses/6385/quizzes/45691

### Concern

Both answers to the question "How do we parameterize different parts of our routes?" are correct because they both use the < and > to parameterize a variable in the URL. The only difference is one distinguishes the data type.

### Suggested Changes

Remove the < and > from the answer that you are considering wrong.

**Comment by lizbur10** [comment]
@NomadLyfe  because of a mistake that was made when the quiz was created, your issue is attached to the wrong repo. I'm going to transfer this issue to the correct repo and close it here. Thanks for posting it!
